#Server
server:
  port: 9090
# DataSource Config
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql #，每次啟動程式，程式都會運行schema.sql檔，對資料庫的資料操作
    data: classpath:db/data.sql #，每次啟動程式，程式都會運行data.sql檔，對資料庫的資料操作
    url: jdbc:h2:~/test #配置h2資料庫的連接位址
    sql-script-encoding: UTF-8
    username: sa
    password: sa
  h2:
    console:
      enabled: true #開啟web console功能
  # redis配置
  redis:
    # redis資料庫索引（預設為0），我們使用索引為3的資料庫，避免和其他資料庫衝突
    database: 0
    # redis伺服器地址（默認為localhost）
    host: 127.0.0.1
    # redis埠（默認為6379）
    port: 6379
    # redis訪問密碼（預設為空）
    password: 
    # redis連接逾時時間（單位為毫秒）
    timeout: 8000
    # redis連接池配置
    lettuce:
      pool: #連接池配置
        max-active: 1000 #連接池最大連接數
        max-wait: -1 #連接池最大阻塞等待時間
        max-idle: 8 #連接池中的最大空閒連接數
        min-idle: 0 #連接池中的最小空閒連接數
  # cache配置
  cache:
    #指定緩存類型為redis
    type: redis
    redis:
      time-to-live: 60000 #緩存超時時間 單位：ms
      key-prefix: CACHE_   #緩存key首碼
      use-key-prefix: true #是否開啟緩存key首碼
      cache-null-values: true #緩存空值，解決緩存穿透問題
#  cache:
#    type: ehcache #redis
#    ehcache:
#      config: classpath:/ehcache.xml
# mybatis配置
mybatis:
  # 配置檔案所在位置
#  config-location: classpath:MybatisConfig.xml
  # 對映檔案所在位置
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration: 
    #開啟二級緩存
    cache-enabled: true
    #開啟mybatis駝峰式命名規則自動轉換
    map-underscore-to-camel-case: true
    #用於控制台列印sql語句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #Entity所在位置
  type-aliases-package: com.edison.demo.model
# log配置
logging:
  level:
    org.springframework.web: DEBUG
    com.edison.demo: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application-debug.log